# Build stage
FROM golang:1.24.1-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o /out/redirect ./cmd/redirect

# Run stage
FROM alpine:latest
WORKDIR /app

COPY --from=builder /out/redirect ./

EXPOSE 8085

CMD ["./redirect"]
