# Build stage
FROM golang:1.24.1-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

WORKDIR /app/server/admin
RUN go build -o /admin-app main.go

# Run stage
FROM alpine:latest
WORKDIR /app

COPY --from=builder /admin-app .
COPY docs ./docs

CMD ["./admin-app"]
