# Build stage
FROM golang:1.24.1-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

WORKDIR /app/server/redirect
RUN go build -o /redirect-app main.go

# Run stage
FROM alpine:latest
WORKDIR /app

COPY --from=builder /redirect-app .

EXPOSE 8085

CMD ["./redirect-app"]
