-- +goose Up
CREATE TABLE users (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Stored lowercase by the application; the login ID.
    email      text        NOT NULL CONSTRAINT uni_users_email UNIQUE,
    password   text        NOT NULL,
    name       text        NOT NULL,
    verified   boolean     NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE shortened_urls (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    long_url   text        NOT NULL,
    short_code text        NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uidx_shortened_urls_short_code ON shortened_urls (short_code);
-- Per-user listing, newest first.
CREATE INDEX idx_shortened_urls_owner_id ON shortened_urls (created_by, id);

-- One row per click. Deleting a link deletes its clicks.
CREATE TABLE url_redirects (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_url_id bigint      NOT NULL REFERENCES shortened_urls (id) ON DELETE CASCADE,
    short_code   text        NOT NULL,
    created_by   bigint      NOT NULL,
    agent        text        NOT NULL DEFAULT '',
    ip_address   text        NOT NULL DEFAULT '',
    metadata     jsonb       NOT NULL DEFAULT '{}',
    created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_url_redirects_url_time ON url_redirects (short_url_id, created_at);
CREATE INDEX idx_url_redirects_created_by ON url_redirects (created_by);

-- +goose Down
DROP TABLE url_redirects;
DROP TABLE shortened_urls;
DROP TABLE users;
